site:
  title: Caleb Carlson - Documentation
  url:  https://inf0rmatiker.github.io/
  start_page: docs-site:ROOT:index.adoc
output:
  dir: ./docs
content:
  sources:
    - url: .
      branches: [HEAD]
ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
