site_name: "inf0rmatiker docs"
site_description: "GitHub Pages for inf0rmatiker"
site_author: "Caleb Carlson"
docs_dir: docs/
repo_name: "inf0rmatiker"
repo_url: "https://github.com/inf0rmatiker/inf0rmatiker.github.io"
nav:
    - Home: index.md
theme:
  name: 'material'
