= Compiling Lustre

:toc: auto
:showtitle:

* https://wiki.lustre.org/Compiling_Lustre[Compiling Lustre Documentation]
* https://wiki.whamcloud.com/pages/viewpage.action?pageId=258179277[Walk-through: Build Lustre MASTER on RHEL/Rocky linux 8.7 from Git]
* https://wiki.whamcloud.com/display/PUB/Rebuilding+the+Lustre-client+rpms+for+a+new+kernel[Rebuilding the Lustre Client RPMs for a New Kernel]

Here we'll be using Rocky Linux 8.6 Minimal as our base installation medium.

== Prerequisites and Dependencies

=== Setup Rocky 8.6 Repositories

Out of the box, Rocky 8.6 points to Rocky 8.8 repositories for packages. This will become problematic if we try to install
packages that depend on a newer version of the kernel, as they'll install that newer version of the `kernel-core` and `kernel-devel`.
The kernel version Rocky 8.6 runs out of the box is `4.18.0-372.9.1.el8.x86_64`:

[,console]
----
[root@mawenzi-04 ~]# uname -r
4.18.0-372.9.1.el8.x86_64
----

However, if you try to install packages like `kernel-devel`, you'll see it will find the one for a newer kernel.

[,console]
----
[root@mawenzi-04 ~]# dnf search -v kernel-devel
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.7.0
cachedir: /var/cache/dnf
Last metadata expiration check: 1:09:48 ago on Fri 21 Jul 2023 10:34:42 AM MDT.
=================================================================== Name Exactly Matched: kernel-devel ====================================================================
kernel-devel.x86_64 : Development package for building kernel modules to match the kernel
Repo        : baseos
Matched from:
Provide    : kernel-devel = 4.18.0-477.15.1.el8_8
----

This will cause incompatibilities down the road for compiling Lustre since we'll essentially be compiling it for a newer kernel version, the one Rocky 8.8 uses.

Instead, we need to change Rocky 8.6's `yum` repository configurations over to use the _true_ https://dl.rockylinux.org/vault/rocky/8.6/[Rocky 8.6 Vault repositories].

To view what repositories are currently in enabled, run `yum repolist -v`. Note how all the repos referenced are for Rocky 8.8.

[,console]
----
[root@mawenzi-04 lustre-release]# yum repolist -v
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
YUM version: 4.7.0
cachedir: /var/cache/dnf
Last metadata expiration check: 0:12:12 ago on Fri 21 Jul 2023 10:34:42 AM MDT.
Repo-id            : appstream
Repo-name          : Rocky Linux 8 - AppStream
Repo-revision      : 8.8
Repo-distro-tags      : [cpe:/o:rocky:rocky:8]:  ,  , 8, L, R, c, i, k, n, o, u, x, y
Repo-updated       : Wed 19 Jul 2023 10:08:22 AM MDT
Repo-pkgs          : 7,550
Repo-available-pkgs: 6,103
Repo-size          : 12 G
Repo-mirrors       : https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=AppStream-8
Repo-baseurl       : http://mirrors.rit.edu/rocky/8.8/AppStream/x86_64/os/ (43 more)
Repo-expire        : 172,800 second(s) (last: Fri 21 Jul 2023 10:34:40 AM MDT)
Repo-filename      : /etc/yum.repos.d/Rocky-AppStream.repo

Repo-id            : baseos
Repo-name          : Rocky Linux 8 - BaseOS
Repo-revision      : 8.8
Repo-distro-tags      : [cpe:/o:rocky:rocky:8]:  ,  , 8, L, R, c, i, k, n, o, u, x, y
Repo-updated       : Wed 19 Jul 2023 10:08:27 AM MDT
Repo-pkgs          : 1,857
Repo-available-pkgs: 1,855
Repo-size          : 2.3 G
Repo-mirrors       : https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=BaseOS-8
Repo-baseurl       : http://mirrors.rit.edu/rocky/8.8/BaseOS/x86_64/os/ (43 more)
Repo-expire        : 172,800 second(s) (last: Fri 21 Jul 2023 10:34:41 AM MDT)
Repo-filename      : /etc/yum.repos.d/Rocky-BaseOS.repo

Repo-id            : extras
Repo-name          : Rocky Linux 8 - Extras
Repo-revision      : 1689203561
Repo-distro-tags      : [cpe:/o:rocky:rocky:8]:  ,  , 8, L, R, c, i, k, n, o, u, x, y
Repo-updated       : Wed 12 Jul 2023 05:12:41 PM MDT
Repo-pkgs          : 52
Repo-available-pkgs: 52
Repo-size          : 3.3 M
Repo-mirrors       : https://mirrors.rockylinux.org/mirrorlist?arch=x86_64&repo=extras-8
Repo-baseurl       : https://rocky-linux-us-west4.production.gcp.mirrors.ctrliq.cloud/pub/rocky//8.8/extras/x86_64/os/ (43 more)
Repo-expire        : 172,800 second(s) (last: Fri 21 Jul 2023 10:34:42 AM MDT)
Repo-filename      : /etc/yum.repos.d/Rocky-Extras.repo
Total packages: 9,459
----

We'll switch these over to the Rocky 8.6 repos.

Create a new file `/etc/yum.repos.d/Rocky-86-Development.repo` by running the following command

[,bash]
----
cat >> /etc/yum.repos.d/Rocky-86-Development.repo << EOF
# Rocky-AppStream.repo
[appstream86]
name=Rocky Linux $releasever - AppStream
#mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=AppStream-$releasever
baseurl=https://dl.rockylinux.org/vault/rocky/8.6/AppStream/x86_64/os/
gpgcheck=1
enabled=1
countme=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial

# Rocky-BaseOS.repo
[baseos86]
name=Rocky Linux $releasever - BaseOS
#mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=BaseOS-$releasever
baseurl=https://dl.rockylinux.org/vault/rocky/8.6/BaseOS/x86_64/os/
gpgcheck=1
enabled=1
countme=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial

# Rocky-Devel.repo
[devel86]
name=Rocky Linux $releasever - Devel WARNING! FOR BUILDROOT AND KOJI USE
#mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=Devel-$releasever
baseurl=https://dl.rockylinux.org/vault/rocky/8.6/Devel/x86_64/os/
gpgcheck=1
enabled=0
countme=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial

# Rocky-Extras.repo
[extras86]
name=Rocky Linux $releasever - Extras
#mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=extras-$releasever
baseurl=https://dl.rockylinux.org/vault/rocky/8.6/extras/x86_64/os/
gpgcheck=1
enabled=1
countme=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial

# Rocky-PowerTools.repo
[powertools86]
name=Rocky Linux $releasever - PowerTools
#mirrorlist=https://mirrors.rockylinux.org/mirrorlist?arch=$basearch&repo=PowerTools-$releasever
baseurl=https://dl.rockylinux.org/vault/rocky/8.6/PowerTools/x86_64/os/
gpgcheck=1
enabled=1
countme=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rockyofficial
EOF
----

Then, disable the original 8.8 repos, and enable the 8.6 repos

[,bash]
----
dnf config-manager --disable appstream baseos extras
dnf config-manager --enable appstream86 baseos86 extras86 powertools86
----

Now, when we search for `kernel-devel`, we see the correct kernel version:

[,console]
----
[root@mawenzi-04 yum.repos.d]# dnf search kernel-devel -v
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, needs-restarting, playground, repoclosure, repodiff, repograph, repomanage, reposync
DNF version: 4.7.0
cachedir: /var/cache/dnf
Rocky Linux 8 - AppStream                                                                                                                  1.4 MB/s |  11 MB     00:07
Rocky Linux 8 - BaseOS                                                                                                                     3.7 MB/s | 9.0 MB     00:02
Rocky Linux 8 - Extras                                                                                                                     8.0 kB/s |  12 kB     00:01
=================================================================== Name Exactly Matched: kernel-devel ====================================================================
kernel-devel.x86_64 : Development package for building kernel modules to match the kernel
Repo        : baseos86
Matched from:
Provide    : kernel-devel = 4.18.0-372.32.1.el8_6
----

=== Install Prerequisite Packages

Install prerequisite software tools on the build server:

First, install DNF plugins package.

[,bash]
----
dnf install -y dnf-plugins-core
----

Next, install Extra Packages for Enterprise Linux (EPEL) release.

[,bash]
----
dnf install -y epel-release
----

Install the "Development Tools" group. This will also pull in the `kernel-headers` 
and `kernel-devel` packages as dependencies.

[,bash]
----
dnf groupinstall -y "Development Tools"
----

Install the remaining dependecies for compiling the Lustre client

[,bash]
----
dnf install -y         \
    audit-libs-devel   \
    bc                 \
    binutils-devel     \
    git                \
    json-c-devel       \
    kernel-debug-devel \
    kernel-rpm-macros  \
    libaio-devel       \
    libattr-devel      \
    libblkid-devel     \
    libmount           \
    libmount-devel     \
    libnl3-devel       \
    libselinux-devel   \
    libssh-devel       \
    libtirpc-devel     \
    libuuid-devel      \
    llvm-toolset       \
    pciutils-devel     \
    ncurses-devel      \
    openssl-devel      \
    perl               \
    perl-devel         \
    python39           \
    python3-devel      \
    python3-docutils   \
    redhat-lsb         \
    texinfo            \
    texinfo-tex        
----

Update `dnf`:

[bash]
----
dnf update
----

=== Clone Lustre Repository

Clone the Lustre repository from whamcloud.

[,bash]
----
git clone https://review.whamcloud.com/fs/lustre-release
----

== Compiling the Lustre Client

THIS IS AS FAR AS I'VE GOTTEN FOR A CLEAN LUSTRE BUILD ANYTHING FURTHER NEEDS TO BE RE-DONE

TODO: Clean up the following section and verify

[,bash]
----
dnf install asciidoc audit-libs-devel automake bc binutils-devel \
    bison device-mapper-devel elfutils-devel elfutils-libelf-devel expect \
    flex gcc gcc-c++ git glib2 glib2-devel hmaccalc keyutils-libs-devel \
    krb5-devel ksh libattr-devel libblkid-devel libselinux-devel libtool \
    libuuid-devel libyaml-devel lsscsi make ncurses-devel net-snmp-devel \
    net-tools newt-devel numactl-devel parted patchutils pciutils-devel \
    perl-ExtUtils-Embed pesign redhat-rpm-config rpm-build \
    systemd-devel tcl tcl-devel tk tk-devel wget xmlto yum-utils zlib-devel
dnf install -y  kabi-dw ncurses-devel \
    newt-devel numactl-devel openssl-devel   \
    xmlto xz-devel elfutils-libelf-devel libcap-devel libcap-ng-devel \
    llvm-toolset libyaml libyaml-devel  kernel-abi-whitelists
checkout b2_15
sh autogen.sh
_TOPDIR=`rpm --eval %{_topdir}`
cd $HOME/lustre-release
make distclean
./configure --enable-dist --disable-server --enable-client
make dist
mkdir -p $_TOPDIR/SOURCES/
cp lustre-*.tar.gz $_TOPDIR/SOURCES/
rpmbuild -bs --without servers lustre-dkms.spec
rpmbuild --rebuild --without servers $_TOPDIR/SRPMS/lustre-client-dkms-*.src.rpm
dnf install -y kernel-debug-devel dkms


dnf install -y \
    asciidoc audit-libs-devel automake bc \
    binutils-devel bison device-mapper-devel elfutils-devel \
    elfutils-libelf-devel expect flex gcc gcc-c++ git \
    glib2 glib2-devel hmaccalc keyutils-libs-devel krb5-devel ksh \
    libattr-devel libblkid-devel libselinux-devel libtool \
    libuuid-devel libyaml-devel lsscsi make ncurses-devel \
    net-snmp-devel net-tools newt-devel numactl-devel \
    parted patchutils pciutils-devel perl-ExtUtils-Embed \
    pesign python3-devel redhat-rpm-config rpm-build systemd-devel \
    tcl tcl-devel tk tk-devel wget xmlto yum-utils zlib-devel
----

[,bash]
----
dnf install kernel-devel rpm-build make libtool zlib-devel libselinux-devel openssl-devel
----

=== DKMS Lustre Client Builds

