= Git

:toc: auto
:showtitle:

Git is a widely-used, open-source tool for managing versions of a project.

* https://git-scm.com/[Git Site]
* https://git-scm.com/doc[Git Documentation and Reference Guides]
* https://en.wikipedia.org/wiki/Git[Wikipedia - Git]

== Installation

https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Get Started Installing Git]

== Configuration

=== Shell Aliases

Add these aliases to your `.bashrc` or `.zshrc` to make life easier:

[,bash]
----
# Git
alias clone="git clone"
alias checkout="git checkout"
alias update="git fetch && git pull"
alias push="git push"
alias commit="git commit -a"
alias add="git add"
alias pull="git pull"
alias status="git status"
alias log="git log --all --decorate --oneline --graph"
alias cherry-pick="git cherry-pick"
export GITHUB_TOKEN="<YOUR_GITHUB_ACCESS_TOKEN>"
export PAT=$GITHUB_TOKEN
----

=== Set Global Git User Name/Email

https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git[GitHub: Setting your commit email in Git]

[,bash]
----
git config --global user.name "FIRST_NAME LAST_NAME"
git config --global user.email "MY_NAME@example.com"
----

=== Git Commit Signing

This section describes how to create an SSH key, and configure Git to use it to sign commits.

First, generate a new SSH key:

[,console]
----
ssh-keygen \          
    -t ed25519 \
    -C "cacarlson@nvidia.com" \
    -f "${HOME}/.ssh/id_ed25519_nvidia_git_signing" \
    -P ""
----

Upload the `.pub` signing key to GitHub: https://github.com/settings/keys
Choose `New SSH Key`, set title to something descriptive i.e. "Nvidia MacBook Signing Key",
then choose `Key Type: Signing Key`, and copy/paste the contents of the `${HOME}/.ssh/id_ed25519_nvidia_git_signing.pub`
into the `Key` field. You'll need to authenticate with 2FA to add this to your account.

Now, make Git aware of it. This sets the options globally, but you can remove the `--global` flag and
just run these commands in your repo directory to set the Git config options for that repo.

[,console]
----
git config --global user.name "Caleb Carlson"
git config --global user.email "cacarlson@nvidia.com"
git config --global user.signingkey "~/.ssh/id_ed25519_nvidia_git_signing.pub"
git config --global gpg.format ssh
git config --global commit.gpgsign true
----

Next, we need to create an https://git-scm.com/docs/git-config#Documentation/git-config.txt-gpgsshallowedSignersFile[allowed signers file].
This is a file containing ssh public keys which you are willing to trust.

[,console]
----
mkdir -p ~/.config/git
echo "cacarlson@nvidia.com $(cat ~/.ssh/id_ed25519_nvidia_git_signing.pub)" > ~/.config/git/allowed-signers
git config --global gpg.ssh.allowedSignersFile ~/.config/git/allowed-signers
----

From now on, when you `git commit`, you can do it like this: `git commit -a -s -S`, and it will sign your commit
using your signing key you configured.

Then, you can view your new commit via `git log --show-signature`:

[,console]
----
commit a45186c94b76fc605b73ff93c93a7882420e1da2 (HEAD -> master)
Good "git" signature for cacarlson@nvidia.com with ED25519 key SHA256:mWy0S6deDF8dXu13zQXvnhnrA/BGEl6i6kuABEq2A6c
Author: Caleb Carlson <cacarlson@nvidia.com>
Date:   Tue Apr 21 09:46:37 2026 -0600

    Add git signing docs, pt. 1

    Signed-off-by: Caleb Carlson <cacarlson@nvidia.com>
----

==== References

* https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key[GitHub: Generating a new GPG key]
* https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key[GitHub: Telling Git about your signing key]
* https://stackoverflow.com/questions/77935996/git-commit-s-silently-fails-to-sign-and-continues-to-commit-when-using-ssh[Git Commit Silently Fails to Sign]

== Commands

Useful `git` commands for managing a repository.

=== Sign-off on a Commit

NOTE: This is _different_ from _signing_ a commit.

https://volunteer.coscup.org/docs/en/dev/how-to-signoff/[COSCUP Volunteer Docs: How to Sign-off Commits]

Commit messages should be formatted with the first name, last name, and email address authorized with GitHub for that repository.

[,console]
----
Commit message.

first_name last_name <email_address>
----

For example,

----
Generate vendor dependencies at build-time

* Remove vendor/ directory
* Generate vendor/ during build
* Gitignore vendor/ dir
* Add go mod vendor to make build
* Add go mod vendor to docker build
* Use go mod download instead of vendor

Signed-off-by: Caleb Carlson <ccarlson355@gmail.com>
----

=== Delete a Branch

Delete a local branch:

[,bash]
----
git branch --delete <branchname>
----

NOTE: Make sure you switch to another branch before doing this so you're not stranded on a deleted branch.

Example:

[,console]
----
➜  hpc-sp-kjplat-img git:(bugfix/SSM-4489) ✗ checkout master                    
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
➜  hpc-sp-kjplat-img git:(master) ✗ git branch --delete bugfix/SSM-4489
warning: deleting branch 'bugfix/SSM-4489' that has been merged to
         'refs/remotes/origin/bugfix/SSM-4489', but not yet merged to HEAD.
Deleted branch bugfix/SSM-4489 (was 8d7abea).
----

Delete the remote branch:

[,bash]
----
git push origin --delete <branchname>
----

Example:

[,console]
----
➜  hpc-sp-kjplat-img git:(master) ✗ git push origin --delete kjplat-634
To github.hpe.com:hpe/hpc-sp-kjplat-img.git
 - [deleted]         kjplat-634
----

You can also use the GitHub repository web UI to delete the remote branch.

* xref:docs-site:learning:version-control/github/github.adoc#delete_a_branch[Delete a Remote Branch Using GitHub]

=== Push Repo to New Upstream

If you've cloned out a repo from one source, like GitLab, and would like to push it to a blank GitHub repo,
you can do so easily by adding an `upstream` remote to your Git workflow.

https://docs.gitlab.com/ee/user/project/repository/forking_workflow.html[Git Forking Workflow]

1. Add an upstream
+
[,bash]
----
git remote add upstream git@github.com:inf0rmatiker/antora-site-ui.git
----
2. Push your master or main branch to your new upstream
+
[,bash]
----
git push upstream master
----
