= Linux Networking

== Utilities

* `ip`
* `ifcfg`
* `nmcli`

== Interfaces

=== List Ethernet Interfaces on Host

You can use `lspci` to list PCI-based Ethernet devices on a system.

[,console]
----
[root@mawenzi-04 ~]# lspci | grep -i ethernet
c6:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
c6:00.1 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
c6:00.2 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
c6:00.3 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
----

=== Bringing Interfaces Up/Down

https://tldp.org/HOWTO/Linux+IPv6-HOWTO/ch05s02.html[Reference]

Two methods can be used to bring interfaces up or down.

NOTE: This does not persist across boots. Once you reboot the node, the link will return to its default state.

Using `ip`

----
# ip link set dev <interface> up
# ip link set dev <interface> down
----

Examples:

[,bash]
----
ip link set dev eth0 up
ip link set dev eth0 down
----

Using `ifconfig``

----
# /sbin/ifconfig <interface> up
# /sbin/ifconfig <interface> down
----

Examples:

[,bash]
----
/sbin/ifconfig eth0 up
/sbin/ifconfig eth0 down
----

== Hostname

Set hostname using `hostnamectl`

[,bash]
----
hostnamectl set-hostname NAME
----

Set hostname at boot time by editing the grub boot parameters and adding `hostname=NAME`

== Proxies

Set proxy environment for HPE LR1: See xref:docs-site:learning:linux/networking/proxies.adoc[Proxies]

== Firewalls

Disable the `firewalld` firewall daemon:

[,bash]
----
systemctl stop firewalld
systemctl disable firewalld
----

Disable SELinux

[,bash]
----
setenforce 0
----

== RHEL NetworkManager

The newer style of managing Linux networking, particularly in Rocky Linux 9.X going forward. The older `ifconfig` network scripts are no longer being used.

* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/networking_guide/getting_started_with_networkmanager[RHEL: Getting Started with NetworkManager]

